<a href="https://colab.research.google.com/github/yeabwang/pytorch_bootcamp/blob/main/00_getting_started.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

In [ ]:
torch.__version__


'2.8.0+cu126'

## Whats Tensor
Tensor is multi dimensional numerical representation, which can be used to represenent various data as texts, images, audios and so on.

Based on their dimension we can divide them into four main parts:

- Scalars → 0D tensor

- Vectors → 1D tensor (shape:
(n,))

- Matrices → 2D tensor (shape:
(m,n))

- Higher-order tensors → 3D+

``` torch.tensor(7)``` - This will create a scalar tensor \n
```torch.tensor([3,224,224])``` - This will create a vector tensor.[link text](https://)

In [ ]:
# Scalar tensors

scalar_tensor = torch.tensor(7)

print(scalar_tensor) # Printing the value of our tensor
print(scalar_tensor.shape) # Printing shape of our created tensor
print(scalar_tensor.ndim) # Printing the dimension of our tensor
print(scalar_tensor.item()) # Get the actual value of our tensor in int format

tensor(7)
torch.Size([])
0
7


In [ ]:
# Vector tensors

vector_tensor = torch.tensor([3,4])

print(vector_tensor)
print(vector_tensor.shape)
print(vector_tensor.ndim)


tensor([3, 4])
torch.Size([2])
1


In [ ]:
# Matrix tensors

matrix = torch.tensor([[3,4], [5,6]])

print(matrix)
print(matrix.ndim)
print(matrix.shape)
print(matrix[0])

tensor([[3, 4],
        [5, 6]])
2
torch.Size([2, 2])
tensor([3, 4])


In [2]:
# Higher order tensor

higher_dim = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
higher_dim = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(higher_dim)
print(higher_dim.shape)
print(higher_dim.ndim)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])
2


In [11]:
# Tensor Operations

## Element Wise operations

higher_dim * 10

# Matrix wise multiplication ( a = (row,col) and b = (row,col) here "a col" has to match with "b row")
random_mat = torch.randint(low=1, high=10, size=(3,3))

torch.matmul(random_mat, higher_dim)

tensor([[ 81,  99, 117],
        [ 32,  40,  48],
        [ 54,  72,  90]])

In [13]:
linear = torch.nn.Linear(in_features=3, out_features=4)

x = linear(random_mat.float())
print(x)

tensor([[-3.6481,  4.1951,  6.3941, -2.2261],
        [-0.6880,  2.7681, -0.5617, -2.3045],
        [-1.3869,  4.2551,  3.6974, -5.7819]], grad_fn=<AddmmBackward0>)


In [20]:
my_arr = torch.arange(1,10) # supports only one d dimn

my_arr.min(), my_arr.max(), my_arr.mean(dtype=torch.float32), my_arr.median(), my_arr.argmax(), my_arr.argmin()

(tensor(1), tensor(9), tensor(5.), tensor(5), tensor(8), tensor(0))

In [24]:
my_arr.dtype, my_arr.type(dtype=torch.float16)

(torch.int64,
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16))

In [66]:
# Reshaping, stacking, squeezing and unsqueezing

## reshaping
to_reshape = torch.randint(1,10, size=(3,4))
to_reshape.reshape(shape=(2,6)) # reshape the matrix without actually changing the data and also keeps the original

## stacking
to_be_stacked_a = torch.randint(low=1, high=10, size=(1,10))
to_be_stacked_b = torch.randint(low=1, high=10, size=(1,10))
to_be_stacked_c = torch.randint(low=1, high=10, size=(1,10))

stacked_col = torch.stack([to_be_stacked_a,to_be_stacked_b,to_be_stacked_c], dim=1)
stacked_row = torch.stack([to_be_stacked_a,to_be_stacked_b,to_be_stacked_c], dim=0)

# print(stacked_row)
# print(stacked_col)

## Squeeze
x = torch.zeros(1, 3, 1, 5)   # shape (1,3,1,5)
print(x.shape)                # torch.Size([1,3,1,5])

y = torch.squeeze(x)          # removes dims of size 1
print(y.shape)                # torch.Size([3,5])

## Unsquezze
z = torch.unsqueeze(x, dim=0)
print(z.shape)

# Permute - shares the same data
k =  torch.permute(higher_dim,(1,0))
print(f"Before permute \n {higher_dim}")
print(f"After permute \n {k}")
print("hhh")
higher_dim[0:2, 0:1]

torch.Size([1, 3, 1, 5])
torch.Size([3, 5])
torch.Size([1, 1, 3, 1, 5])
Before permute 
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
After permute 
 tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])
hhh


tensor([[1],
        [4]])

In [73]:
## Working with numpy

num_arr = np.random.randint(low=1,high=10, size=(2,3))
changed_to_tensor = torch.from_numpy(num_arr).type(torch.float32)
changed_back = torch.Tensor.numpy(changed_to_tensor)
num_arr, changed_to_tensor, changed_back


(array([[2, 6, 7],
        [6, 7, 3]]),
 tensor([[2., 6., 7.],
         [6., 7., 3.]]),
 array([[2., 6., 7.],
        [6., 7., 3.]], dtype=float32))

In [79]:
# adding seed
random_seed = 3
torch.manual_seed(random_seed)
arr_a = torch.randint(low=1, high=5, size=(2,3))
torch.manual_seed(random_seed)
arr_b = torch.randint(low=1, high=5, size=(2,3))

print(arr_a)
print(arr_b)

tensor([[3, 1, 2],
        [4, 1, 1]])
tensor([[3, 1, 2],
        [4, 1, 1]])


Working with GPU


In [2]:
!nvidia-smi

Mon Sep 29 07:45:25 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:00:04.0 Off |                    0 |
| N/A   32C    P0             46W /  400W |       0MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+-----

In [11]:
torch.cuda.is_available(), torch.cuda.device_count()

device = "cuda" if torch.cuda.is_available() else "cpu"

normal_tensor = torch.randint(low=2,high=100, size=(3,4))
print(normal_tensor, normal_tensor.device)
gpu_tensor = normal_tensor.to(device)
print(gpu_tensor, gpu_tensor.device)

# If you want to convert them back to cpu in cases where you want to work with numpy
returned_back = gpu_tensor.cpu().numpy()
returned_back

tensor([[ 9, 24, 93,  3],
        [60,  6, 24, 10],
        [46, 80, 76,  4]]) cpu
tensor([[ 9, 24, 93,  3],
        [60,  6, 24, 10],
        [46, 80, 76,  4]], device='cuda:0') cuda:0


array([[ 9, 24, 93,  3],
       [60,  6, 24, 10],
       [46, 80, 76,  4]])