<a href="https://colab.research.google.com/github/yeabwang/pytorch_bootcamp/blob/main/pytorch_bootcamp_homework_1ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [4]:
print(torch.__version__)
print(device)

2.8.0+cu126
cpu


In [23]:
# Question 1: Create a random tensor with shape (7, 7).

first_random = torch.rand(size=(7,7), dtype=torch.float32)
first_random

tensor([[0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038],
        [0.6511, 0.7745, 0.4369, 0.5191, 0.6159, 0.8102, 0.9801],
        [0.1147, 0.3168, 0.6965, 0.9143, 0.9351, 0.9412, 0.5995],
        [0.0652, 0.5460, 0.1872, 0.0340, 0.9442, 0.8802, 0.0012],
        [0.5936, 0.4158, 0.4177, 0.2711, 0.6923, 0.2038, 0.6833],
        [0.7529, 0.8579, 0.6870, 0.0051, 0.1757, 0.7497, 0.6047],
        [0.1100, 0.2121, 0.9704, 0.8369, 0.2820, 0.3742, 0.0237]])

In [24]:
# Question 2:  Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)
second_tensor = torch.rand(size=(1,7), dtype=torch.float32)
multiplied = torch.matmul(first_random, second_tensor.T)
multiplied

tensor([[1.2239],
        [2.0847],
        [1.9002],
        [0.9408],
        [1.5213],
        [1.3606],
        [0.8780]])

In [25]:
# Question 3: Set the random seed to 0 and do exercises 2 & 3 over again.

torch.random.manual_seed(0)
first_tensor = torch.rand(size=(7,7), dtype=torch.float32)
second_tensor = torch.rand(size=(1,7), dtype=torch.float32)

second_mul = torch.matmul(first_tensor,second_tensor.T)
print(second_mul)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


In [4]:
# Checking GPU
print(device)

!nvidia-smi

cuda
Mon Sep 29 08:24:52 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:00:04.0 Off |                    0 |
| N/A   31C    P0             44W /  400W |       5MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+

In [8]:
# Question 4: Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?
torch.manual_seed(1234)
gpu_random = torch.rand(size=(1,6), dtype=torch.float32)
gpu_random

tensor([[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006]])

In [13]:
# Question 5: Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this).
torch.manual_seed(1234)

gpu_tensor_1 = torch.rand(size=(2,3), dtype=torch.float32).to(device)
gpu_tensor_2 = torch.rand(size=(2,3), dtype=torch.float32).to(device)

gpu_tensor_1,gpu_tensor_2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [15]:
# Question 6: Perform a matrix multiplication on the tensors you created in 5 (again, you may have to adjust the shapes of one of the tensors).

gpu_tensors_mat = torch.matmul(gpu_tensor_1,gpu_tensor_2.T)
gpu_tensors_mat

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [21]:
# Question 7: Find the maximum and minimum values of the output of 6.
print("Max: ",gpu_tensors_mat.max().item())
print("Min: ", gpu_tensors_mat.min().item())

Max:  0.5617256760597229
Min:  0.3647301197052002


In [23]:
# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

torch.manual_seed(7)

original_tensor = torch.rand(size=(1, 1, 1, 10))
print(original_tensor, original_tensor.shape)

removed_tensor = original_tensor.squeeze()
print(removed_tensor, removed_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
